version: '3.2' 

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
      - 50070:50070
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop
    env_file:
      - ./envs/hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    container_name: datanode1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./envs/hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    container_name: datanode2
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./envs/hadoop.env
      
  hue:
    container_name: filebrowser
    image: bde2020/hdfs-filebrowser:3.11
    ports:
      - 8089:8088
    environment:
      - NAMENODE_HOST=namenode
     
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop3.1
    container_name: spark-master
    ports:
      - 8083:8080
      - 4040:4040
    environment: 
      - PYSPARK_PYTHON=python3
      - PYTHONIOENCODING=utf8
    env_file:
      - ./envs/hadoop.env
    volumes:
      - spark_master:/hadoop/dfs/data

  spark-worker1:
    image: bde2020/spark-worker:2.4.0-hadoop3.1
    container_name: spark-worker1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8084:8081
    env_file:
      - ./envs/hadoop.env
    depends_on:
      - spark-master


volumes:
  hadoop_namenode:
  spark_master:
  hadoop_datanode1:
  hadoop_datanode2:
